### ISSUE TITLE
赛规疑问

### ISSUE THREAD

**Issue by nt-lcf** [hwxchy/MDKA_car_fight#1]
1、我看规则介绍了只分了小学组和中学组，所以小高组也是按小学组的规则，不需要到绿色标记处完成核电装置能量补给任务吧？
2、遥控阶段的时候，对面已经推到基地的矿石还可以去争夺吗？

**Comment by hwxchy** [comment]
1.按照小学规则。
2.时间允许的话可以争夺对方基地的矿石。
